compressionLevel: 0

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: pnp

packageExtensions:
  "@apollo/experimental-nextjs-app-support@*":
    dependencies:
      graphql: "*"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
