# Configuration docs: https://yarnpkg.com/configuration/yarnrc

# Use exact versions of new dependencies by default
defaultSemverRangePrefix: ''

# TODO: Experiment with pnpm or zero-install linkers
nodeLinker: node-modules

plugins:
  # upgrade-interactive support
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

# TODO: See if we can remove .yarn/releases for yarn v4.  Works on local machine but breaks on CI with yarn 3.2.2
yarnPath: .yarn/releases/yarn-3.2.4.cjs
