# Configuration: https://yarnpkg.com/configuration/yarnrc

yarnPath: .yarn/releases/yarn-3.2.2.cjs

# TODO: Experiment with pnpm or zero-install linkers
nodeLinker: node-modules

# Use exact versions of new dependencies by default
defaultSemverRangePrefix: ""