compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: pnp
pnpMode: strict

packageExtensions:
  '@apollo/experimental-nextjs-app-support@*':
    dependencies:
      graphql: '*'

yarnPath: .yarn/releases/yarn-4.5.1.cjs
