compressionLevel: 0

defaultSemverRangePrefix: ''

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  '@apollo/experimental-nextjs-app-support@*':
    dependencies:
      graphql: '*'

yarnPath: .yarn/releases/yarn-4.4.0.cjs
