name: CI

on:
  push:
    branches:
      - main
      # Renovate needs to see test status before PR is created
      - 'renovate/**'
  pull_request: {}

jobs:
  ci:
    name: 'Scan & Test'
    runs-on: ubuntu-latest
    environment: hedvig-hope-staging
    env:
      NEXT_PUBLIC_API_URL: ${{ vars.NEXT_PUBLIC_API_URL }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate GraphQL types
        run: yarn codegen

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck

      - name: Test
        run: yarn test
