export { Checkbox } from './components/Checkbox/Checkbox'
export { BurgerButton } from './components/BurgerButton/BurgerButton'
export { Menu } from './components/Menu/Menu'
export type { MenuTheme } from './components/Menu/Menu'
export { HedvigLogo } from './components/HedvigLogo/HedvigLogo'
export { Button, LinkButton } from './components/Button/Button'
export type { ButtonVariant, ButtonColors, ButtonSize } from './components/Button/Button'
export { Separate } from './components/Separate'
export { Space } from './components/Space'
export { InputBase } from './components/InputBase'
export type { InputBaseProps } from './components/InputBase'
export { InputField } from './components/InputField/InputField'
export type { InputFieldProps } from './components/InputField/InputField'
export { InputStepper } from './components/InputStepper/InputStepper'
export { Heading as HeadingOLD } from './components/Heading/Heading'
export { Heading } from './components/HeadingNew/HeadingNew'

export type { Level } from './lib/media-query'
export { mq, useBreakpoint } from './lib/media-query'

export { getCDNFonts, fonts } from './lib/theme/typography'
export { theme, getColor } from './lib/theme/theme'
export { ThemeProvider } from './lib/theme/ThemeProvider'
export { globalStyles } from './lib/globalStyles'

export { MailIcon } from './icons/MailIcon'
export { PhoneIcon } from './icons/PhoneIcon'
export { ArrowForwardIcon } from './icons/ArrowIcon'
export { CrossIcon } from './icons/CrossIcon'
export { ChevronIcon } from './icons/Chevron'
