compressionLevel: 0
# Workaround for https://github.com/yarnpkg/berry/issues/2583
checksumBehavior: ignore

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    dependencies:
      typescript: "*"
  react-hot-toast@*:
    dependencies:
      csstype: "*"
  react-smooth@*:
    dependencies:
      prop-types: "*"
  react-swipeable-views-utils@*:
    dependencies:
      react: "*"
  root-workspace-0b6124@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
