import { createSprinkles, defineProperties } from '@vanilla-extract/sprinkles'
import { createSubset } from '../utils/createSubset'
import { mediaQueries } from './media'
import { tokens } from './theme.css'
import { fontSizes } from './typography'

const textColors = {
  textPrimary: tokens.colors.textPrimary,
  textSecondary: tokens.colors.textSecondary,
  textSecondaryOnGray: tokens.colors.textSecondaryOnGray,
  textTertiary: tokens.colors.textTertiary,
  textTranslucentPrimary: tokens.colors.textTranslucentPrimary,
  textTranslucentSecondary: tokens.colors.textTranslucentSecondary,
  textTranslucentTertiary: tokens.colors.textTranslucentTertiary,
  textDisabled: tokens.colors.textDisabled,
  textNegative: tokens.colors.textNegative,
  textGreen: tokens.colors.textGreen,
  textAmber: tokens.colors.textAmber,
  textRed: tokens.colors.textRed,
  signalBlueText: tokens.colors.signalBlueText,
  signalRedText: tokens.colors.signalRedText,
  signalGreenText: tokens.colors.signalGreenText,
  signalAmberText: tokens.colors.signalAmberText,
} as const

// Only a fraction of the space tokens are used (the most used ones) so we can reduce
// the number of classes generated by sprinkles.
const spaceTokensSubset = createSubset(tokens.space, [
  'none',
  'xxs',
  'xs',
  'sm',
  'md',
  'lg',
  'xl',
  'xxl',
  'xxxl',
])
const mediaQueriesSubset = createSubset(mediaQueries, ['sm', 'md', 'lg'])

const unresponsiveProperties = defineProperties({
  properties: {
    alignItems: ['flex-start', 'center', 'flex-end', 'stretch'],
    alignSelf: ['center'],
    justifyContent: ['center', 'space-between', 'flex-end'],
    textAlign: ['left', 'center', 'right'],
    color: textColors,
    display: ['flex', 'grid', 'none'],
    flexDirection: ['row', 'column'],
    flexGrow: [1],
    gap: { ...spaceTokensSubset },
    marginInline: spaceTokensSubset,
    marginTop: spaceTokensSubset,
    marginBottom: spaceTokensSubset,
    marginLeft: spaceTokensSubset,
    marginRight: spaceTokensSubset,
    overflow: ['hidden'],
    padding: spaceTokensSubset,
    paddingBlock: spaceTokensSubset,
    paddingInline: spaceTokensSubset,
    paddingTop: spaceTokensSubset,
    paddingBottom: spaceTokensSubset,
    paddingLeft: spaceTokensSubset,
    paddingRight: spaceTokensSubset,
  },
  shorthands: {
    mx: ['marginLeft', 'marginRight'],
    my: ['marginTop', 'marginBottom'],
    ml: ['marginLeft'],
    mr: ['marginRight'],
    mt: ['marginTop'],
    mb: ['marginBottom'],
    px: ['paddingLeft', 'paddingRight'],
    py: ['paddingTop', 'paddingBottom'],
    pl: ['paddingLeft'],
    pr: ['paddingRight'],
    pt: ['paddingTop'],
    pb: ['paddingBottom'],
  },
})

const responsiveProperties = defineProperties({
  conditions: {
    _: {},
    ...mediaQueriesSubset,
  },
  defaultCondition: '_',
  properties: {
    fontSize: fontSizes,
  },
})

export const sprinkles = createSprinkles(unresponsiveProperties, responsiveProperties)
export type Sprinkles = Parameters<typeof sprinkles>[0]
