name: Cypress

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # Install NPM dependencies, cache them correctly and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          command: yarn e2e-onboarding:headless
