name: Update repo diagram

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: temp-repo-diagram.svg
          excluded_paths: 'ignore,.github'
          should_push: false

      - name: Checkout assets branch
        run: |
          git branch assets
          git checkout assets
          git pull origin assets

      - name: Overwrite diagram
        run: mv ./temp-repo-diagram.svg ./repo-diagram.svg

      - name: Add & commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'repo-diagram.svg'
          message: 'Repo visualizer: updated diagram'
