name: Update repo diagram

on:
  push:
    branches:
      - main
      
  workflow_dispatch:

jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update diagram
        uses: githubocto/repo-visualizer@main
        with:
          output_file: temp-repo-diagram.svg
          excluded_paths: 'ignore,.github'
          should_push: false

      - name: Checkout assets branch
        run: git checkout assets

      - name: Overwrite diagram
        run: git mv --force ./temp-repo-diagram.svg ./repo-diagram.svg

      - name: Add & commit
        uses: EndBug/add-and-commit@v7
        with:
          add: 'repo-diagram.svg'
          message: 'Repo visualizer: updated diagram'
          branch: assets
          pull: NO-PULL
