name: Deploy translations from Lokalise

on:
  workflow_dispatch:

jobs:
  deploy_translations:
    runs-on: ubuntu-latest
    steps:
      - name: Install Lokalise CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/lokalise/lokalise-cli-2-go/master/install.sh | sh

      - name: Export translations
        run: |
          ./bin/lokalise2 \
            -t "${{ secrets.LOKALISE_TOKEN }}" \
            --project-id 743091915e9da969db9340.20943733 \
            file download \
            --format json \
            --export-sort first_added \
            --add-newline-eof \
            --replace-breaks=false \
            --original-filenames=false \
            --bundle-structure './locales/%LANG_ISO%/common.json' \
            --placeholder-format icu \
            --include-tags web-onboarding \
            --indentation 2sp \
            --filter-langs 'en,da_DK,en_DK,sv_SE,en_SE,nb_NO,en_NO' \
            --language-mapping '[
              {"original_language_iso": "en","custom_language_iso": "default"},
              {"original_language_iso": "da_DK","custom_language_iso": "dk"},
              {"original_language_iso": "en_DK","custom_language_iso": "dk-en"},
              {"original_language_iso": "sv_SE","custom_language_iso": "se"},
              {"original_language_iso": "en_SE","custom_language_iso": "se-en"},
              {"original_language_iso": "nb_NO","custom_language_iso": "no"},
              {"original_language_iso": "en_NO","custom_language_iso": "no-en"}
            ]'

      - name: Upload to S3
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: 'locales'
          destination_dir: 'web-onboarding'
